### ISSUE TITLE
Crash when checking Clear on application exit

### ISSUE THREAD

**Issue by gatocinza** [scoute-dich/browser#515] opened 2021-05-30 17:57 UTC
Hello,

The browser (v. 7.4.3) crashes everytime I open the _Settings_ menu after checking _Clear on application exit_ together with all the boxes above this option.
I'm sure about the bug 'cause it stopped crashing once I cleared the app cache.
I'm using a Lenovo A2016b30 with Android 6.0.

I hope been helpful. Have a good day/night and keep it doing ;) the app works great and have really nice features. Willing to use the Dark mode soon.

**Comment by scoute-dich** [comment] 2021-06-04 18:40
I can not reproduce this. Can you please confirm, that on version 7.4.4 this problem is still present? If yes, please provide a logcat. Then I can help.

**Comment by gatocinza** [comment] 2021-06-14 15:10
Hi. I updated the 7.4.4 version and it keeps happening. So here I leave the logcat.
Nevertheless, I'm not knowledgeable with android and programming, so I hope did a gob job.
First I cleared the app's cache, then I flushed the logcat and start it by checking the *Settings>Delete* menu options, exit the app and finally went back to *Settings* menu where it crashes.
[logcat.txt](https://github.com/scoute-dich/browser/files/6649381/logcat.txt)

**Comment by scoute-dich** [comment] 2021-06-21 06:29
[app-debug.apk.zip](https://github.com/scoute-dich/browser/files/6684514/app-debug.apk.zip)
Thanks for the logcat. Above is an attached apk. If anyone wants, he can test it and report back.

**Comment by scoute-dich** [comment] 2021-06-22 14:12
I just released a new version (7.5) if this bug still is not solved, please reopen the issue. Thanks for your help.

**Comment by scoute-dich** [comment] 2021-06-22 14:14
I just released a new version (7.5) if this bug still is not solved, please report it here. Otherwise, I'll close this issue.

**Comment by gatocinza** [comment] 2021-06-27 17:22
Hi. Sorry for be late.
I'm afraid to say it doesn't work yet :c I installed the 7.5 version and now it don't let me access to Settings menu even after cache-flushing. Here I leave a logcat: 
[logcatv2.txt](https://github.com/scoute-dich/browser/files/6722012/logcatv2.txt)

P.S.: Nice icon in the new version, by the way.

**Comment by woheller69** [comment] 2021-06-27 21:04
I cannot reproduce that with V7.6WIP

**Comment by scoute-dich** [comment] 2021-06-29 10:03
I also ca not reproduce. I changed depreciated theme resources. Perhaps this helps:
[app-debug.apk.zip](https://github.com/scoute-dich/browser/files/6732516/app-debug.apk.zip)

**Comment by gatocinza** [comment] 2021-06-29 23:02
> I also ca not reproduce. I changed depreciated theme resources. Perhaps this helps:
> [app-debug.apk.zip](https://github.com/scoute-dich/browser/files/6732516/app-debug.apk.zip)

Didn't work neither. Re-install 7.4.4 flushing cache and it let me open Settings again.

**Comment by scoute-dich** [comment] 2021-08-18 08:37
Is this issue still from relevance? We are now on version 8.2 ...

**Closed** 2021-11-08 19:29 UTC
Labels: bug, help wanted
