### ISSUE TITLE
Website crash

### ISSUE THREAD

**Issue by oonet** [scoute-dich/browser#665] opened 2021-09-01 23:29 UTC
FOSS Browser v8.2
Android 10.0

Always crashes on the following link:

https://www.costco.com/pc-laptops.html?screen-type=non-touchscreen&refine=||Screen_Type_attr-Non-touchscreen

**Comment by woheller69** [comment] 2021-09-02 11:15
for me it works, no crash

**Comment by tusch001** [comment] 2021-09-02 15:42
im on Android 6.01
FOSS Browser 8.2 starts loading, shows title in navigation bar then the browser crashes before the site is finally loaded (the green ring indicator over the left button stands at 10 oClock). 
```
09-02 17:30:10.516  1307  1318 I ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=de.foss.browser/de.baumann.browser.activity.BrowserActivity bnds=[288,1162][432,1280]} from uid 10073 on display 0

09-02 17:30:10.557  1307  1317 I ActivityManager: Start proc 9966:de.foss.browser/u0a111 for activity de.foss.browser/de.baumann.browser.activity.BrowserActivity

09-02 17:30:11.494  1307  1325 I ActivityManager: Displayed de.foss.browser/de.baumann.browser.activity.BrowserActivity: +948ms

09-02 17:30:17.835  9966  9966 F libc    : Fatal signal 5 (SIGTRAP), code -6 in tid 9966 (de.foss.browser)

09-02 17:30:17.942   581   581 F DEBUG   : pid: 9966, tid: 9966, name: de.foss.browser  >>> de.foss.browser <<<

09-02 17:30:18.387  1307 10033 W ActivityManager:   Force finishing activity de.foss.browser/de.baumann.browser.activity.BrowserActivity

09-02 17:30:18.532  1307  4553 I WindowState: WIN DEATH: Window{dab4c6d u0 de.foss.browser/de.baumann.browser.activity.BrowserActivity}

09-02 17:30:18.543  1307  4587 I ActivityManager: Process de.foss.browser (pid 9966) has died
```

**Comment by tusch001** [comment] 2021-09-02 15:45
Sorry, forgot to turn on "verbose":
```
---- 02.09.2021 5:43:54 nachm. ----

09-02 17:27:26.120  1307  4578 I ActivityManager: START u0 {act=android.intent.action.VIEW dat=file:///storage/emulated/0/LogcatX/de.foss.browser.txt typ=text/plain flg=0x10000000 cmp=in.mfile/com.nmmedit.nmm.TextEditorActivity (has extras)} from uid 10113 on display 0

09-02 17:28:04.405  1307  4578 I ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=de.foss.browser/de.baumann.browser.activity.BrowserActivity bnds=[288,1162][432,1280]} from uid 10073 on display 0

09-02 17:28:04.436  1307  4589 I ActivityManager: Start proc 9358:de.foss.browser/u0a111 for activity de.foss.browser/de.baumann.browser.activity.BrowserActivity

09-02 17:28:13.277  9358  9358 F libc    : Fatal signal 5 (SIGTRAP), code -6 in tid 9358 (de.foss.browser)

09-02 17:28:13.330   581   581 F DEBUG   : pid: 9358, tid: 9358, name: de.foss.browser  >>> de.foss.browser <<<

09-02 17:28:13.968  1307  4589 I WindowState: WIN DEATH: Window{d169cad u0 de.foss.browser/de.baumann.browser.activity.BrowserActivity}

09-02 17:28:13.980  1307  4584 I ActivityManager: Process de.foss.browser (pid 9358) has died

09-02 17:28:17.442  1307  3236 I ActivityManager: Start proc 9435:de.foss.browser/u0a111 for activity de.foss.browser/de.baumann.browser.activity.BrowserActivity

09-02 17:28:25.994  9435  9435 F libc    : Fatal signal 5 (SIGTRAP), code -6 in tid 9435 (de.foss.browser)

09-02 17:28:26.099   581   581 F DEBUG   : pid: 9435, tid: 9435, name: de.foss.browser  >>> de.foss.browser <<<

09-02 17:28:26.579  1307  9557 W ActivityManager:   Force finishing activity de.foss.browser/de.baumann.browser.activity.BrowserActivity

09-02 17:28:26.748  1307  4585 I WindowState: WIN DEATH: Window{dd0774d u0 de.foss.browser/de.baumann.browser.activity.BrowserActivity}

09-02 17:28:26.756  1307  1318 I ActivityManager: Process de.foss.browser (pid 9435) has died

09-02 17:28:49.998  1307  4585 I ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10300000 cmp=de.foss.browser/de.baumann.browser.activity.BrowserActivity} from uid 10073 on display 0

09-02 17:28:50.075  1307  4587 I ActivityManager: Start proc 9573:de.foss.browser/u0a111 for activity de.foss.browser/de.baumann.browser.activity.BrowserActivity

09-02 17:29:00.953  9573  9573 F libc    : Fatal signal 5 (SIGTRAP), code -6 in tid 9573 (de.foss.browser)

09-02 17:29:01.057   581   581 F DEBUG   : pid: 9573, tid: 9573, name: de.foss.browser  >>> de.foss.browser <<<

09-02 17:29:01.565  1307  9694 W ActivityManager:   Force finishing activity de.foss.browser/de.baumann.browser.activity.BrowserActivity

09-02 17:29:01.782  1307  1318 I WindowState: WIN DEATH: Window{95a8400 u0 de.foss.browser/de.baumann.browser.activity.BrowserActivity}

09-02 17:29:01.793  1307  3758 I ActivityManager: Process de.foss.browser (pid 9573) has died

09-02 17:29:35.816  1307  3758 I ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10300000 cmp=de.foss.browser/de.baumann.browser.activity.BrowserActivity} from uid 10073 on display 0

09-02 17:29:35.904  1307  4589 I ActivityManager: Start proc 9799:de.foss.browser/u0a111 for activity de.foss.browser/de.baumann.browser.activity.BrowserActivity

09-02 17:29:43.600  9799  9799 F libc    : Fatal signal 5 (SIGTRAP), code -6 in tid 9799 (de.foss.browser)

09-02 17:29:43.704   581   581 F DEBUG   : pid: 9799, tid: 9799, name: de.foss.browser  >>> de.foss.browser <<<

09-02 17:29:44.185  1307  9866 W ActivityManager:   Force finishing activity de.foss.browser/de.baumann.browser.activity.BrowserActivity

09-02 17:29:44.356  1307  4578 I WindowState: WIN DEATH: Window{760daa4 u0 de.foss.browser/de.baumann.browser.activity.BrowserActivity}

09-02 17:29:44.371  1307  4553 I ActivityManager: Process de.foss.browser (pid 9799) has died

09-02 17:30:10.516  1307  1318 I ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=de.foss.browser/de.baumann.browser.activity.BrowserActivity bnds=[288,1162][432,1280]} from uid 10073 on display 0

09-02 17:30:10.557  1307  1317 I ActivityManager: Start proc 9966:de.foss.browser/u0a111 for activity de.foss.browser/de.baumann.browser.activity.BrowserActivity

09-02 17:30:17.835  9966  9966 F libc    : Fatal signal 5 (SIGTRAP), code -6 in tid 9966 (de.foss.browser)

09-02 17:30:17.942   581   581 F DEBUG   : pid: 9966, tid: 9966, name: de.foss.browser  >>> de.foss.browser <<<

09-02 17:30:18.387  1307 10033 W ActivityManager:   Force finishing activity de.foss.browser/de.baumann.browser.activity.BrowserActivity

09-02 17:30:18.532  1307  4553 I WindowState: WIN DEATH: Window{dab4c6d u0 de.foss.browser/de.baumann.browser.activity.BrowserActivity}

09-02 17:30:18.543  1307  4587 I ActivityManager: Process de.foss.browser (pid 9966) has died

09-02 17:31:17.340  1307  4585 I ActivityManager: START u0 {act=android.intent.action.VIEW dat=file:///storage/emulated/0/LogcatX/de.foss.browser.txt typ=text/plain flg=0x10000000 cmp=in.mfile/com.nmmedit.nmm.TextEditorActivity (has extras)} from uid 10113 on display 0

09-02 17:31:31.018  1307  3234 I ActivityManager: START u0 {act=android.intent.action.VIEW dat=file:///storage/emulated/0/LogcatX/de.foss.browser2.txt typ=text/plain flg=0x10000000 cmp=in.mfile/com.nmmedit.nmm.TextEditorActivity (has extras)} from uid 10113 on display 0

09-02 17:33:36.117  1307  4585 I ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=de.foss.browser/de.baumann.browser.activity.BrowserActivity bnds=[288,1162][432,1280]} from uid 10073 on display 0

09-02 17:33:36.159  1307  3758 I ActivityManager: Start proc 10509:de.foss.browser/u0a111 for activity de.foss.browser/de.baumann.browser.activity.BrowserActivity

09-02 17:41:16.466  1307  3236 I ActivityManager: START u0 {act=android.intent.action.VIEW dat=file:///storage/emulated/0/LogcatX/de.foss.browser2.txt typ=text/plain flg=0x10000000 cmp=in.mfile/com.nmmedit.nmm.TextEditorActivity (has extras)} from uid 10113 on display 0

09-02 17:43:03.243  1307  4587 I ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=de.foss.browser/de.baumann.browser.activity.BrowserActivity bnds=[288,1162][432,1280]} from uid 10073 on display 0

09-02 17:43:11.553 10509 10509 I chatty  : uid=10111(de.foss.browser) expire 64 lines

09-02 17:43:15.312 12081 12081 I chatty  : uid=10111(de.foss.browser) expire 472 lines

09-02 17:43:15.987 10509 10509 F libc    : Fatal signal 5 (SIGTRAP), code -6 in tid 10509 (de.foss.browser)

09-02 17:43:16.042   581   581 F DEBUG   : pid: 10509, tid: 10509, name: de.foss.browser  >>> de.foss.browser <<<

09-02 17:43:16.467  1307 12118 W ActivityManager:   Force finishing activity de.foss.browser/de.baumann.browser.activity.BrowserActivity

09-02 17:43:16.596  1307  4607 I WindowState: WIN DEATH: Window{f7083a1 u0 de.foss.browser/de.baumann.browser.activity.BrowserActivity}

09-02 17:43:16.608  1307  1318 I ActivityManager: Process de.foss.browser (pid 10509) has died

09-02 17:43:24.039  1307  4585 I ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=de.foss.browser/de.baumann.browser.activity.BrowserActivity bnds=[288,1162][432,1280]} from uid 10073 on display 0

09-02 17:43:24.068  1307  4607 I ActivityManager: Start proc 12153:de.foss.browser/u0a111 for activity de.foss.browser/de.baumann.browser.activity.BrowserActivity

09-02 17:43:24.127 12153 12153 I chatty  : uid=10111(de.foss.browser) expire 42 lines

09-02 17:43:24.347 12153 12168 I chatty  : uid=10111(de.foss.browser) expire 1 line

09-02 17:43:24.636 12153 12174 I chatty  : uid=10111(de.foss.browser) expire 1 line

09-02 17:43:24.664 12153 12179 I chatty  : uid=10111(de.foss.browser) expire 1 line

09-02 17:43:24.699 12153 12189 I chatty  : uid=10111(de.foss.browser) expire 1 line

09-02 17:43:24.726 12153 12181 I chatty  : uid=10111(de.foss.browser) expire 1 line

09-02 17:43:24.729 12153 12190 I chatty  : uid=10111(de.foss.browser) expire 3 lines

09-02 17:43:24.791 12153 12198 I chatty  : uid=10111(de.foss.browser) expire 2 lines

09-02 17:43:24.986  1307  1325 I ActivityManager: Displayed de.foss.browser/de.baumann.browser.activity.BrowserActivity: +930ms

09-02 17:43:31.187 12153 12153 I chatty  : uid=10111(de.foss.browser) expire 20 lines

09-02 17:43:32.510 12153 12153 F libc    : Fatal signal 5 (SIGTRAP), code -6 in tid 12153 (de.foss.browser)

09-02 17:43:32.618   581   581 F DEBUG   : pid: 12153, tid: 12153, name: de.foss.browser  >>> de.foss.browser <<<

09-02 17:43:33.108  1307 12220 W ActivityManager:   Force finishing activity de.foss.browser/de.baumann.browser.activity.BrowserActivity

09-02 17:43:33.311  1307  3236 I WindowState: WIN DEATH: Window{eb8a7e6 u0 de.foss.browser/de.baumann.browser.activity.BrowserActivity}

09-02 17:43:33.328  1307  4589 I ActivityManager: Process de.foss.browser (pid 12153) has died

---- 02.09.2021 5:43:54 nachm. ----
```

**Comment by tusch001** [comment] 2021-09-06 05:06
I think it is the 2 letters `||` in the url. In [RFC3986](https://www.ietf.org/rfc/rfc3986.txt) they are not mentioned as special characters so I think they should be encoded. I can load the page withot the last part of the url.

**Comment by scoute-dich** [comment] 2021-11-24 20:35
Hi,

is this issue still present in version 8.4? I can not reproduce this issue. Otherwise I'll close this.

**Comment by oonet** [comment] 2021-11-25 01:25
In 8.4, the link still does not load correctly. The following page comes 
up instead:

https://customerservice.costco.com/app/answers/detail/a_id/9228/kw/cookies

**Comment by tusch001** [comment] 2021-11-26 17:17
`is this issue still present in version 6.4?`
yes and no

The link works in 6.4 when you allow JS, Cookies, third-party (the profile with the hollow shield for trusted sites, then paste above link again). The cookie-message is a redirection. 
But also: after 1 - 2 s after loading the page (JS finished loading?) the browser crashes (repeatedly, every time).
Android 6

```
---- 26.11.2021 6:14:29 nachm. ----

11-26 18:14:01.479 22182 22182 W System.err: 	at de.baumann.browser.database.FaviconHelper.getDomain(FaviconHelper.java:157)

11-26 18:14:01.479 22182 22182 W System.err: 	at de.baumann.browser.database.FaviconHelper.getFavicon(FaviconHelper.java:82)

11-26 18:14:01.479 22182 22182 W System.err: 	at de.baumann.browser.view.CompleteAdapter.getView(CompleteAdapter.java:215)

11-26 18:14:01.525 22182 22182 W System.err: 	at de.baumann.browser.database.FaviconHelper.getDomain(FaviconHelper.java:157)

11-26 18:14:01.525 22182 22182 W System.err: 	at de.baumann.browser.database.FaviconHelper.getFavicon(FaviconHelper.java:82)

11-26 18:14:01.525 22182 22182 W System.err: 	at de.baumann.browser.view.CompleteAdapter.getView(CompleteAdapter.java:215)

11-26 18:14:02.250 22182 22182 W System.err: 	at de.baumann.browser.database.FaviconHelper.getDomain(FaviconHelper.java:157)

11-26 18:14:02.250 22182 22182 W System.err: 	at de.baumann.browser.database.FaviconHelper.getFavicon(FaviconHelper.java:82)

11-26 18:14:02.250 22182 22182 W System.err: 	at de.baumann.browser.database.FaviconHelper.setFavicon(FaviconHelper.java:167)

11-26 18:14:02.250 22182 22182 W System.err: 	at de.baumann.browser.view.NinjaWebView.updateFavicon(NinjaWebView.java:496)

11-26 18:14:02.250 22182 22182 W System.err: 	at de.baumann.browser.browser.NinjaWebChromeClient.onProgressChanged(NinjaWebChromeClient.java:41)

11-26 18:14:02.524 22182 22182 W System.err: 	at de.baumann.browser.database.FaviconHelper.getDomain(FaviconHelper.java:157)

11-26 18:14:02.524 22182 22182 W System.err: 	at de.baumann.browser.database.FaviconHelper.getFavicon(FaviconHelper.java:82)

11-26 18:14:02.524 22182 22182 W System.err: 	at de.baumann.browser.view.NinjaWebView.setFavicon(NinjaWebView.java:615)

11-26 18:14:02.524 22182 22182 W System.err: 	at de.baumann.browser.browser.NinjaWebChromeClient.onReceivedIcon(NinjaWebChromeClient.java:127)

11-26 18:14:02.525 22182 22182 W System.err: 	at de.baumann.browser.database.FaviconHelper.getDomain(FaviconHelper.java:157)

11-26 18:14:02.525 22182 22182 W System.err: 	at de.baumann.browser.database.FaviconHelper.addFavicon(FaviconHelper.java:60)

11-26 18:14:02.525 22182 22182 W System.err: 	at de.baumann.browser.view.NinjaWebView.setFavicon(NinjaWebView.java:615)

11-26 18:14:02.525 22182 22182 W System.err: 	at de.baumann.browser.browser.NinjaWebChromeClient.onReceivedIcon(NinjaWebChromeClient.java:127)

11-26 18:14:02.526 22182 22182 W System.err: 	at de.baumann.browser.database.FaviconHelper.addFavicon(FaviconHelper.java:60)

11-26 18:14:02.526 22182 22182 W System.err: 	at de.baumann.browser.view.NinjaWebView.setFavicon(NinjaWebView.java:615)

11-26 18:14:02.526 22182 22182 W System.err: 	at de.baumann.browser.browser.NinjaWebChromeClient.onReceivedIcon(NinjaWebChromeClient.java:127)

11-26 18:14:03.820   582   582 F DEBUG   : pid: 22182, tid: 22182, name: baumann.browser  >>> de.baumann.browser <<<

11-26 18:14:04.340  1327 22269 W ActivityManager:   Force finishing activity de.baumann.browser/.activity.BrowserActivity

11-26 18:14:04.480  1327  3439 I WindowState: WIN DEATH: Window{910a11b u0 de.baumann.browser/de.baumann.browser.activity.BrowserActivity}

11-26 18:14:04.524  1327  4906 I ActivityManager: Process de.baumann.browser (pid 22182) has died

---- 26.11.2021 6:14:29 nachm. ----
```

**Comment by woheller69** [comment] 2021-11-26 17:55
I simplified setFavicon in NinjaWebView. In the past we only checked for bookmarks. Now we are also checking for entries in history and start site. So we can list all entries at once.
There is a less opening and closing the database. Maybe this is the reason for the website crash #665.

**Comment by tusch001** [comment] 2021-11-26 18:27
I cleared everything including database. Now the link works without crashing the browser. Problem solved?
 
BTW: the original link from above is now also redirected to [https://www.costco.com/pc-laptops.html?screen-type=non-touchscreen&refine=%7C%7CScreen_Type_attr-Non-touchscreen](https://www.costco.com/pc-laptops.html?screen-type=non-touchscreen&refine=%7C%7CScreen_Type_attr-Non-touchscreen). Seemed they have fixed the url.

**Comment by tusch001** [comment] 2021-11-27 14:31
A thought:
if the two characters `||` in the initial link were responsible for initial crash (not sure) - is / can be the url checked against allowed characters from RFC3986?

**Comment by scoute-dich** [comment] 2021-12-16 11:28
[app-debug.apk.zip](https://github.com/scoute-dich/browser/files/7726884/app-debug.apk.zip)
Does this solve the problem? I con not reproduce this issue. But it seems, that getting the domain is the problem ...

**Comment by tusch001** [comment] 2021-12-18 14:54
Sorry, can't install apk. Parsing error.

**Comment by scoute-dich** [comment] 2021-12-23 19:59
Does this also happen on v8.7 (which was released today on F-Droid)? Because I can't reproduce it.

**Comment by tusch001** [comment] 2021-12-25 17:29
Sorry, can't test / install. I'm stuck with Android 6.0. F-Droid version says it's 8.6 and I still get parsing errors during installation. So I will stay on 8.41 until I buy a new phone (not in the near future).
Thanks again for this browser.

**Comment by scoute-dich** [comment] 2021-12-27 17:39
Sorry to drop support for your phone.

**Closed** 2021-12-27 17:39 UTC
