### ISSUE TITLE
half screen bug

### ISSUE THREAD

**Issue by cauerego** [scoute-dich/browser#864] opened 2022-02-03 05:22 UTC
some rare and random times the screen render blocks the bottom half of the screen and make the tool bar to disappear.

looks exactly as #817 but without the toolbar and not directly related to "some sites".

might be duplicated of #862 sorry for not searching (now further) for issues this time!

the last time it happened i could get out of it with the back button... and then the bug disappeared.

**Comment by scoute-dich** [comment] 2022-03-04 20:39
Duplicate of #862

**Closed by scoute-dich** 2022-03-04 20:39 UTC
