### ISSUE TITLE
Annoying tab navigation 

### ISSUE THREAD

**Issue by jhoc2000** [scoute-dich/browser#281] opened 2019-06-15 03:29 UTC
The latest version, 6.4 has very annoying tab navigation. One can no longer long press on a tab to change its order and when one comes back to FOSS Browser the last tab is shown rather than the previously opened tab. This is very, very annoying because one has to continuously scroll back to the relevant tab when one returns to FOSS Browser. I'm very tempted to go back to the previous version to eliminate this behaviour. The trouble is that I'll probably lose all my bookmarks. 

Please, please fix this behaviour. Allow long press on a tab to rearrange its order and to go to the previously opened tab when one returns to the app.

**Comment by dkmgfk** [comment] 2019-06-16 15:41
>when one comes back to FOSS Browser the last tab is shown rather than the previously opened tab

I can confirm this, besides long pressing to close tab is not so convienent, as sometimes I need to close multiple tabs at once. The font in address bar seems to have changed a little bit. With some sort of shadow on it.
![Screenshot_20190616-233851_1](https://user-images.githubusercontent.com/47562939/59566249-14ca3f80-9090-11e9-883f-259717e1c93d.png)

A great improvement is the scrolling gesture no longer conflict with other gestures in the history view.

**Comment by scoute-dich** [comment] 2019-06-21 20:46
> One can no longer long press on a tab to change its order and when one comes back to FOSS Browser the last tab is shown rather than the previously opened tab.

I don't understand. Where did you long press on a tab to change the order? On the overview? When you return to FOSS Browser the last opened tab will be shown (even if you opened it in the background).

> The font in address bar seems to have changed a little bit. With some sort of shadow on it.

This will be fixed with next update.

> A great improvement is the scrolling gesture no longer conflict with other gestures in the history view.

Thanks. ;-)

**Comment by tusch001** [comment] 2019-06-21 22:18
Hi
Just tested the thing with losing focus after changing to another app in the debug-app from the other post - still present:
Pictures for clarification (ignore the half cut pictures - will write about it in the other issue):

picture before: second tab from left has focus / is open

![Focus on second tab from left](https://user-images.githubusercontent.com/46721195/59953900-85070580-9482-11e9-9e8e-8f8e374081cf.png)

switching to another app and coming back: the topmost tab of the stack is open (far right)
![After change to other app and coming back - focus on topmost tab on stack](https://user-images.githubusercontent.com/46721195/59954057-3148ec00-9483-11e9-8463-1fc3f5d950e6.png)


Just to let you know.

**Comment by jhoc2000** [comment] 2019-06-22 00:02
I call it the tab view. If one touches the thing to the left of the URL at the bottom of the screen one is presented with all the tabs (see attached image). If I long press on one of those tabs it is closed. Previously, long pressing on the tab would allow one to move the tab to the left or right. It is very annoying that this behaviour has been changed. 

Also, when one was viewing a tab, let's say the zucchini recipe in the attached image, and then one opened another app ,when one retuned to the FOSS browser the right most tab is shown, eg the duckduckgo tab in the attached image, rather than the most recently opened tab, the zucchini recipe. This is very annoying. Logically, the most recently opened tab should be presented when one returns to the FOSS browser.

I look forward to the next version where these corrections are made.

John.

**Comment by scoute-dich** [comment] 2019-06-22 10:10
Now I understand. I even didn't know that was possible (rearranging tabs). I switched from a third party library (Dynamic GridView), to the native Android GridView. So I don't think, that this feature will be reimplemented, since I want as minimal depencies as possible.

I'll take a look in the second issue,  concerning the last opened tab.

**Comment by scoute-dich** [comment] 2019-06-28 15:36
Is fixed with latest commit. Thanks again for reporting this.

**Closed by scoute-dich** 2019-06-28 15:36 UTC

**Comment by jhoc2000** [comment] 2019-06-28 23:44
Great. Thank you so much for your prompt reply and response.
