### ISSUE TITLE
Browser does not store tabs

### ISSUE THREAD

**Issue by enwokoma** [scoute-dich/browser#75] opened 2018-01-24 13:57 UTC
Well, I noticed another bug lately, this browser clears all open tabs and starts from beginning after I close and restart the app!

**Comment by scoute-dich** [comment] 2018-01-24 14:21
That's not a bug, that's a feature.

**Comment by enwokoma** [comment] 2018-01-24 17:53
Seriously? Seems like it's uncomfortable for some people!

**Comment by scoute-dich** [comment] 2018-01-24 19:23
Yes. You can see it like you want. At the moment I don't have the time to implement this. And since I'm a hobby developer I think I also don't have the abilities. So at the moment there's no chance to implement from my side. Sorry.

**Comment by enwokoma** [comment] 2018-01-25 04:05
Ok. I would see what I can do to contribute to this!

**Comment by jerryn70** [comment] 2018-02-04 07:10
@enwokoma it will be great if you implement the restore tab feature:grinning:

**Comment by ildar** [comment] 2018-02-08 16:41
Looks close to Tab Sessions. Would be awesome! 🙂👍

**Comment by BO41** [comment] 2018-08-07 21:14
@scoute-dich @enwokoma anyone already working on this?
I would suggest saving all open url's in a text file or whatever whenever the app is entering the pause state. And on a new start load those url's.
Or is there a better way?

Where could you find the right files to implement something like this?

**Comment by dragonmaus** [comment] 2019-01-23 22:20
I would argue that this is a mission-critical feature, as Android has a habit of randomly restarting certain open apps. When this happens to FOSS Browser, currently you lose all open tabs, and picking up where you were can be quite painful, if it is possible at all.

**Comment by Tobiplayer3** [comment] 2019-01-24 17:44
I was able to get the restoring of tabs working but it's made in a not really great way, similar to what @BO41 described. Don't really know if it's a sufficient way to implement this feature.

**Comment by scoute-dich** [comment] 2019-04-22 20:58
Still on my big todo list. Still no idea how to implement. Perhaps dynamic shortcuts (only Android 7+) or just set the history as the default content of the overview. Then you could open every last visited websites very fast...

**Comment by scoute-dich** [comment] 2019-08-03 10:10
As I've no time to think about this in the near future I'll close this issue. It is still on my big todo list, but at the moment there are other things more important.

**Closed by scoute-dich** 2019-08-03 10:10 UTC
Labels: Feature request, help wanted
