### ISSUE TITLE
URL/Search bar does not accept url's/search

### ISSUE THREAD

**Issue by dkavlakov** [scoute-dich/browser#7] opened 2017-03-30 09:25 UTC
No matther what i write in URL bar it oppens just an empty DuckDuckGo start page. To open anything i am forced to search it first and hope to find it in results.

**Comment by scoute-dich** [comment] 2017-03-31 13:34
Thanks for reporting and sorry for the late answer. I found the bug just some missing "=". Will be solved in next update. In the meantime, open the main settings and select a preferred search engine.

To open a url you have to type "www." at the beginning.

Regards
Gaukler Faun

**Comment by dkavlakov** [comment] 2017-03-31 16:34
Thank you for the answer. I plan to use your browser as secondary, so waiting next version is not a problem.

> To open a url you have to type "www." at the beginning.

Sorry, this somehow confuses me. I allays thought reasonable way to decide if urlbar contents actually are an url will be to check if it's domain part can be resolved via the dns system.

To serve only url's that start with 'www' is quite inconvenient for a browser. This means it won't be able to open quite big chunk of the actual url's.

**Comment by scoute-dich** [comment] 2017-03-31 17:07
I didn't Len developing. I just followed some tutorials and googled for solutions if there were problems... So I wasn't aware of that problem. Have you any ideas how to solve this?

**Comment by dkavlakov** [comment] 2017-04-03 21:40
Sorry for the delay, was away for a while.
First of all most sites are set to allow to be opened without writing specific sub-domain (even now i browse "github.com", not "www.github.com"). Actually (at least from my experience) sites that have no www sub-domain defined are much more common than sites, that can not be opened without adding www sub-domain. Also many browsers even try to add the www part if plain domain can't be connected via http[s].
On the contrary, many complex sites that have multiple actual servers to provide various services use the sub-domains of those servers to allow direct access to specific services. Some of them are may be accessible via their main page (sometimes - after a lot of writing and clicking, like the support. sub-domains of most hardware manufacturers), while others are accessible only when you write the name directly (for example i commonly have to use looking glasses, that usually are named lg.{domain}.{tld} and can't be reached via the marketing site of the ISP). To make things worse sometimes mobile versions of specific sites have also to be accessed as sub-domains.
Also in places where there is own infrastructure - like large enough companies, or in my case - small datacenter use of multiple sub-domains is unavoidable, as such infrastructure consists of multiple internally available servers/services, that have nothing to do with the public www site.
If you want specific example - one site i commonly use is stats.ripe.net

Generally urlbar parsing seems to follow this pattern:
- Check for scheme prefix. When present open if supported by the browser (http://, https://, ftp:// ...) or send to OS for handling (opening in registered scheme handler) if not supported by browser.
- Check for characters, that can not be present in URL, like 0x00-0x1F, 0x20, 0x22, 0x23, 0x25, 0x3c, 0x3e, 0x7F (there are some other that can be used only in certain places). If present consider it search.
- Parse the domain part and attempt to resolve it as DNS name. If it resolves try to open it as  http://.
- Some browsers then try to open as https://, try to add www. in front, try to append common tld's as .com, .net, .org and if no success try to search. I find attempting https:// good idea (maybe even with setting to prioritize it over http://). but everything else is better to be avoided.

**Comment by scoute-dich** [comment] 2017-04-21 20:20
I attached an apk (just rename zip to apk). Perhaps you can try, if it works as intended. I tried to implement your suggestions. For me it's working.

**Comment by dkavlakov** [comment] 2017-04-24 19:42
While testing attached .apk found glitch with http/https handling.

I try to open custom virtual http domain, say "some.name/path". When i write this in address bar i get "https://some.name/path not found". if i try to force use of http protocol ("http://some.name/path not found" in address bar) the error message becomes ""https://http//some.name/path not found".

**Comment by scoute-dich** [comment] 2017-04-25 11:16
I'm working on it and will upload a new apk these days. Thanks for reporting.

**Comment by scoute-dich** [comment] 2017-04-25 16:15
So. New attempt. Can anyone please try?

[app-debug.zip](https://github.com/scoute-dich/browser/files/955701/app-debug.zip)

**Comment by dkavlakov** [comment] 2017-04-28 23:43
Tested with this url:
10.40.30.254/anime_manga
Still pops up error instead of rolling back to http after finding that there is no https site.
http:// in urlbar is now respected.

**Comment by scoute-dich** [comment] 2017-04-30 19:06
I can't even open this link in browser. What am I doing wrong?

**Comment by Dvaderfun** [comment] 2017-05-01 16:01
All links working fine in this browser. For example: 4pda.ru, google.com. 
Maybe, IP adresses not working and will not work.

**Comment by scoute-dich** [comment] 2017-05-01 19:54
Ok. Then I will close the issue and release the update tomorrow. Thanks to all of you for your help.

**Closed** 2017-05-02 15:06 UTC
