### ISSUE TITLE
Omnibar Covers Page: Fullscreen[Hide Nothing]

### ISSUE THREAD

**Issue by tclaybor** [scoute-dich/browser#30] opened 2017-08-01 09:48 UTC
Version 3.8.1

Steps:

1. Set option to hide status bar, omnibar, both, or nothing to "Hide nothing"
2. Navigate to a page with links in the footer or bottom of the page.
3. Scroll all the way down until stopped

Here's a site you can use: https://www.eff.org/

Notice the "All Updates" button is partially covered.

**Comment by scoute-dich** [comment] 2017-08-03 17:19
At the moment I'm working on bigger changes (nearly go activities will be fragments). When all works as intended. This will be fixed.

_Gesendet von meinem Oneplus A0001 mit [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Closed** 2017-08-03 21:01 UTC
