### ISSUE TITLE
crash after open 

### ISSUE THREAD

**Issue by franco27** [scoute-dich/browser#261] opened 2019-03-14 22:46 UTC
v6.3.1 - Android 7.0 Nougat

no problem with 6.2
since your last update, I can no longer use your web browser.  Every time I want to open it, I click on the icon and immediately afterwards there is a crash.
I deleted the user data, uninstalled and reinstalled the application this problem is not solved.  Suddenly, there is a closing when the application is opened.

**Comment by scoute-dich** [comment] 2019-03-15 06:11
I'll test that with my wife's phone at the weekend. Thanks for reporting.

**Comment by scoute-dich** [comment] 2019-03-15 09:01
I'll close this. IT#s a duplicate of #260.
Over there I've uploaded an apk to test. Thanks for reporting this issue.

**Closed by scoute-dich** 2019-03-15 09:01 UTC
