### ISSUE TITLE
Some pages don't load even with Remote content and adblock exclusion

### ISSUE THREAD

**Issue by wesinator** [scoute-dich/browser#355] opened 2019-12-12 15:29 UTC
Android 9 

loaded https://www.newyorker.com/culture/decade-in-review/the-age-of-instagram-face 
then enabled remote content and added adblock exception for that domain . 

page flashes but does not load . other articles load fine

**Comment by scoute-dich** [comment] 2019-12-17 16:17
I can confirm this. I think that's a problem with the article. It seems to load find, of you disable JavaScript and Cookies. So I assume that a script is the fault. Since all other articles are losing fine, I'll close this issue. Feel free to reopen or comment.

**Closed by scoute-dich** 2019-12-17 16:17 UTC
