### ISSUE TITLE
Bookmarks Deleted With Each Update

### ISSUE THREAD

**Issue by puppykickr** [scoute-dich/browser#298] opened 2019-07-27 05:07 UTC
All bookmarks are deleted with each update of the app.

Therefore, it is pointless to have bookmarks on this browser, as they will just be deleted as soon as the app is updated.

A feature is not a feature at all when it is an annoyance.

If I want to use this browser, the only sane thing to do is to not have any bookmarks stored on it at all.

**Comment by scoute-dich** [comment] 2019-07-27 13:56
That's of course not intended. I don't have that problem, and not heard of it before. Of course I'll look into this.

**Comment by puppykickr** [comment] 2019-07-29 12:16
If you want me to test more on my end, I will.

I currently am running two different OS on three devices.

The app is on all three.

I have been using another app to eliminate the issue with bookmarks.

As it is now, I see no real reason to have bookmarks in FOSS, but I am willing to help troubleshoot.

ZTE 558VL - 7.1.1
Poblano VLE 5 - 8.1.1

**Comment by tusch001** [comment] 2019-08-06 20:53
@scoute-dich 
I was wondering for some time with all my testing that my settings were never saved / exported correctly. While trying to import settings in the new version I just realized that the bookmarks / the database are not correctly saved in the first place:
When the database is backed up there is the file browser_backup/export_bookmarks.txt created. I think it contains only a hash number. Not enough information for several bookmarks. What is missing is browser_backup/databases/Browser.db as in older versions (eg 6.0). I don't think that is correct. 
I was checking different browser versions:
Android 6.0.1 Stock: database missing in all tested versions (6.2, 6.4 and 6.61)
Android 5.1 Stock: only version 6.4 and 6.61 tested - also no Browser.db
Android 7 / LineageOS 14: version 6.6.1 - no db file

I feel sorry for you. Your browser is realy great and you put a lot of effort in it. It's just annoying that things like this can still sneak into the code.

Heads up

**Comment by scoute-dich** [comment] 2019-08-07 07:12
After making a backup of the whole database, there should be a directory "browser_backup" in your "Documents" dir, with following content:
![](https://i.imgur.com/qqgRzPn.png)

databases:
Contains the bookmark database and the database with whitelists and history.

previews:
Containing the preview pictures from the startsite.

exported_bookmarks.txt:
Contains the string which is needed to de- and encrypt your saved passwords. This individual for each installation. So it must be restored too after a clean install.

**Comment by scoute-dich** [comment] 2019-08-07 07:16
In older versions the databases were different. The old backups are not compatible with the new ones. You need all the files above. The old database does not work anymore.

That caused a lot of trouble in the community and many bad ratings on PlayStore.  But I saw no other way.

**Comment by tusch001** [comment] 2019-08-07 08:08
I know you changed the way things are saved. But on my phones there are only the txt-files in the top folder including .nomedia. For testing I deleted the documents folder and created several bookmarks. So there is only an export_bookmarks.txt (no export_cookies.txt ...).

But NO SUBFOLDER "databases". 

Since I didn't make any previews it is ok to have no preview folder. Unfortunately I can't upload pictures (I did't start the thread). I place a screenshot temporarily to
https://nuchi.de/browser.png

Just to make it clear: This screenshot was taken after I created 3 bookmarks in version 6.6.1. This is the way it looks on all the above mentioned combinations of OS and browser version. All those phones are relatively clean. All wiped within the last months. No left over files from previous versions. And I know that there were no older browser versions < 6.4 installed.

I gave my pie tablet my nephew. My sister has an Oreo phone.
If you need I can test on those devices.

**Comment by tusch001** [comment] 2019-08-07 10:30
more information:
The behaviour above is the default. As long as there are no pages saved in overview list. 
Steps to reproduce:
Android 6.0.1 / version 6.6.1
deinstall browser
delete documents folder
install browser
create bookmarks (1 or 2 are sufficient)
make sure they are in the bookmark list
export / save settings --> NO DATABASES
additional info: long press tap doesn't save bookmark in startpage / overview list, so next step:
open one of your bookmarks
menu with 3 dots - disk symbol - save on startpage
make sure there is a entry in the overview page list
export / save settings --> NOW THERE ARE THE DATABASES

**Comment by tusch001** [comment] 2019-08-09 08:19
@scoute-dich
In case you have fixed this issue --> skip

I've never written an app, but for personal learning I went through the code. I came up with an idea why this issue might happen:

With creating backups of the database (file /app/source/main/java/de/baumann/browser/Fragment/Fragment_settings_data.java lines 300-342 where "case R.string.setting_title_export_database" is handled)
you never test if a directory exists. If a user creates only bookmarks and no previews there is no folder /data/data/de.baumann.browser/files (Variable previewsFolder_app).

When you start copying you start creating files / directories in the following order
- export_bookmarks.txt --> ok
- copyDirectory(previewsFolder_app, previewsFolder_backup); --> previewFolder_app doesn't exist if no previews were created
- copyDirectory(databaseFile_app, databaseFile_backup);
- copyDirectory(bookmarkFile_app, bookmarkFile_backup); 

The missing source directory is throwing an exception (logcat below) and - my guess - probably finishes this part of the code. The directory with the databases never gets copied and both files (browser_bookmarks.db and browser_database.db) will be missing.

I think that's why most users don't have a problem - they most likely have some previews. Since I've never used them on my small phone screens the databases folder was never created. That's why I also never was able to successfully import other settings in versions ≥ 6.0. (It was just not that important to me to report it - I should have done it)

I can't do more, I never got around to set up visual studio.


If I'm talking nonsense just be kind enough and forget it.

----- Logcat: ----
08-09 10:09:27.054  1268  4213 I ActivityManager: START u0 {cmp=de.baumann.browser/.Activity.Settings_Activity} from uid 10208 on display 0

08-09 10:09:27.268  1268  2962 I ActivityManager: Displayed de.baumann.browser/.Activity.Settings_Activity: +171ms

08-09 10:09:30.065  1268  4213 I ActivityManager: START u0 {cmp=de.baumann.browser/.Activity.Settings_DataActivity} from uid 10208 on display 0

08-09 10:09:30.288  1268  2962 I ActivityManager: Displayed de.baumann.browser/.Activity.Settings_DataActivity: +202ms

08-09 10:09:37.981  1268  3816 I ActivityManager: START u0 {act=android.settings.APPLICATION_DETAILS_SETTINGS dat=package:de.baumann.browser cmp=com.android.settings/.applications.InstalledAppDetails} from uid 10208 on display 0

08-09 10:09:48.140  6043  6043 W System.err: java.io.FileNotFoundException: /data/data/de.baumann.browser/files: open failed: ENOENT (No such file or directory)

08-09 10:09:48.141  6043  6043 W System.err: 	at de.baumann.browser.Fragment.Fragment_settings_data.copyDirectory(Fragment_settings_data.java:485)

08-09 10:09:48.141  6043  6043 W System.err: 	at de.baumann.browser.Fragment.Fragment_settings_data.access$200(Fragment_settings_data.java:39)

08-09 10:09:48.141  6043  6043 W System.err: 	at de.baumann.browser.Fragment.Fragment_settings_data$13.onClick(Fragment_settings_data.java:322)

**Comment by puppykickr** [comment] 2019-08-09 21:21
I have found that the app called WebApps- available on F-Droid- is a great way to eliminate the bookmark issue altogether.

Once it is set up correctly, it works great when using FOSS Browser as a default browser.

As all the bookmarks are sandboxed in a different app, I no longer need or desire bookmarks in the default browser, as well as not having to log out of any sites.

**Comment by tusch001** [comment] 2019-08-10 08:02
@puppykickr
WebApps is more or less another browser with a different interface and sandbox functionality where you would save your links. I guess most people choose an app because they like the way it works. So I would rather fix the issue with this app than switching to a different app everytime I need a bookmark. If I wanted this functionality there are apps that at the same time sync your bookmarks with eg nextcloud, ...
But it's not a very inconvenient way to open bookmarks.

**Comment by scoute-dich** [comment] 2019-08-10 15:37
I'm going on vacation for two weeks (Rügen, Germany). No. Laptop, no coding. You'll here from me, when I'm back.

**Comment by puppykickr** [comment] 2019-08-11 05:00
@tusch001

The point is that WebApps can be used as a convenient bookmark addition.

This is because of a few things.

Logging in and out is not as concerning as in a normal browser, as each 'bookmark' is sandboxed away from the others.

Each WebApp can share to other WebApps as long as you are logged in on the ones you are sharing to.

Any links you come across while using WebApps will open in your default browser, in this case FOSS.

When you close the final tab in FOSS, you are returned to the WebApp that you were on before.

As the tab set up on FOSS is rather unintuitive, WebApps clears up the confusion quite well, and I still get to enjoy the features of FOSS that work well.

Also, in this way, the troublesome bookmarks and home/startpage issues are no longer even noticed, really.

In fact, FOSS could lose both and there would be no problem with that at all.

And then to top it off, WebApps allows the user to control the third party connections, which is great for security and ad control.

So, the two (FOSS & WebApps) work extremely well with each other.

**Comment by tusch001** [comment] 2019-08-14 16:13
@scoute-dich:

Since we started (a bit off topic from this issue) discussing bookmarks a bit in general I would like to hear your opinion on the following:

One of the main problems with every browser app - esp. on Android - is the storage of bookmarks. If you add different desktop operating systems and numerous browsers it gets complicated synchronizing bookmarks. 
I really like your browser and would like to add an optional feature to synchronize bookmarks across Android and other operating systems. It would also prevent unintended losses of bookmarks with updates. For personal learning and also for my own convenience I'd like to start looking into this.

There are pros and cons of this. 

Some thoughts:

1. Syncing across Android would help users coming from Chrome. It even could promote your browser :-)
These users probably rely on their Google account anyway to sync their bookmarks. So I would "only" have to figure out where the bookmarks are stored and how to access them (com.android.bookmarkprovider or com.android.providers.partnerbookmarks come to mind). The synchronisation would be left to Google.

2. For non google users:
They most likely already have some cloud solution to save their bookmarks - eg in my case I use nextcloud. That's where I want to start. There is a nextcloud server implementation that allows saving bookmarks with simple tags (no sub-tags) and that can be synchronized with (desktop) firefox via a firefox addon. With the way this addon works even firefox sub-tags (subfolders) are saved in simple (one level) tags. That's worth copying for organizing bookmarks more efficiently. From firefox they can be saved as html files, imported to other browsers, ...
There is already a basic open source android app for connecting to a nextcloud server (org.schabi.nxbookmarks) - probably the starting point. But I would rather let Android do the administration of accounts. The nextcloud app (com.nextcloud.client) or davdroid are a good information source how to handle this.
I don't want to handle any passwords. Since Oreo's autofill capability the way to go - in my opinion - are passwort managers. They can handle security better.
Further cloud solutions can eventually be added later on.


The cons:
1. It is and will be your browser. I certainly don't want to step on any toes :-)
That's why I'm asking for your general thoughts on this.

2. Some permissions are needed for this. 
I think you want to keep your browser lean and free. And internet access is already granted :-) But at least for creating accounts one would need additional permissions. I think that's why the NC bookmark app is doing the sync part within the app. But as soon as you start thinking about intervals / sync on or off / multiple accounts (business and private) it's time to let Android handle this.

3. If you could go along with this it's most certainly a long time goal (I have a full time job - and I'm NOT an IT professional). I would have to start small and most likely would need your input (e.g. where to open the windows, how tags should be handled, permissions in general (where to store login credentials), ... ).
And I have no idea yet where to get information about how and where Chrome / Android OS store their bookmarks (The bloatware providers obviously know how to do that).


So:
Are you at all interested in this? 
I can understand if you want to keep your browser simple and the way it is.

I hope the weather get's a bit better for swimming. Enjoy your vaccation.

**Comment by scoute-dich** [comment] 2019-11-11 10:30
So, the question is: is this issue (deleting bookmarks after update)  still there on the actual version? If not I'll close this issue.

**Comment by Datzkaiser** [comment] 2019-12-14 01:08
Yes, the problem is still there. I just updated from 6.6.1 to 6.7 after backing up, then tried to restore, but nothing happens at all. The folder structure is intact though. 
Sorry, but this is a really annoying issue, because it makes updating effectively unusable. 
Running MIUI 10.2 / Android 8.1

**Comment by puppykickr** [comment] 2019-12-28 01:30
@tusch001 

The problem with using a password manager is that the browser must be compatible with autofill.

FOSS is not.

None of my browsers are, in fact.

What happens is that the password winds up getting saved with the browser as the link instead of the actual link, and then the password manager cannot find it.

This is why I cannot use a password manager.

Lightning, WebApps, FOSS, BeHe Explorer all have the same problem.

Even if I go in and edit the info in the password manager, I must save an additional entry for each browser that I wish to open that particular link with.

That means that tbere would be hundreds of entries, most of them repeats (except for the browser used) and then to beat all I would need to keep mental note of which entry is for each browser that I may be using at the time.

I actually even tried this.

It was more hassle and aggrevation than not having a password manager at all.

Autofill never worked effeciently, as it never found the correct entry, and every entry for that browser popped up all at once, and covered the screen.

Then I would have to do a search in the password manager, and enter yet another version of the same login, hoping that it would work the next time.

It is so much easier to just save bookmarks into WebApps, and then make FOSS the default browser.

That way you eliminate the password manager altogether, keep your bookmarks, and any links you touch open with FOSS.

**Comment by Flashwalker** [comment] 2020-03-23 11:25
In my case import imports nothing.

Just made export from old f-droid version, put backup folder to Android/bla-bla/files/, trying import in fresh Google Play version and... nothing happens.

**Comment by scoute-dich** [comment] 2020-06-10 09:41
With next update the bookmark management is handled in a new way. They are now stored in the main database. Export bookmarks as html will also be possible.

If there is still a issue after next update please open a new issue.

**Closed by scoute-dich** 2020-06-10 09:41 UTC
