### ISSUE TITLE
Start/Home Page Substituted With GitHub Page After Update (Again)

### ISSUE THREAD

**Issue by puppykickr** [scoute-dich/browser#311] opened 2019-08-10 18:33 UTC
After an update to 6.6.1 today, once again the startpage/homepage and bookmarks have been erased.

While trying to back out of the GitHub page, I went too far (because there really is no management of individual tabs) and the app closed.

Upon reopening, nothing would load.

In fact, I had to change my default browser just to return to GitHub.to leave this comment.

In order to set the desired startpage, a bookmark must be set and then longpressed, and 'set as startpage' selected, correct?

But, when all bookmarks are erased, then this becomes impossible, and the browser becomes basically useless-  until a lot of resetting is done.

Part of the seriousness of this issue is the fact that not only does the startpage need to be set n the browser yet again, but all of the individual settings for that specific startpage must be set all over again, then saved as a bookmark (again).

For some reason or other, FOSS works better on my 8.1.0

I am not going to update it, however.

As for my 7.1.1 I had to change the default browser back to what I was using before just to get onto GitHub (Lightning).

So, I guess for now, that is where I am at.

I do have two devices running 7.1.1 and only use one of them constantly.

This will allow for more testing on this OS on my part if you desire.
The startpage and bookmarks on the second device are of no consequence, so I can use that one to test further updates.

As for this one, once it is set up again I am leaving it alone.
Because whatever version is on the 8.1.0 works well there, it will also be left alone.

Sorry if I have made much out of this, but my frustration has been so that I can taste it.

**Comment by scoute-dich** [comment] 2019-08-10 18:51
I'm going on vacation for two weeks (Rügen, Germany). No Laptop, no coding. You'll here from me, when I'm back.

**Comment by scoute-dich** [comment] 2019-08-10 18:52
And thanks for contributing. I only have a device running android pie to test. I think that causes a lot of issues for Android versions below.

**Comment by puppykickr** [comment] 2019-08-10 18:56
I just tried to reset everything, and it seems that the browser is not working with any personal startpage settings.

DuckDuckGo, Qwant, Searx, and StartPage are all non-functional.

My personal settings are all non-functional, but still there, from before the update. 
The browser itself is not working at all, save for the search engine that I have set up as the default.

But, because this is not what appears as the startpage, when the browser opens nothing works.

Just a blank, white screen with no searchbar or anything.

The browser will open links from other apps, but as for just opening the browser to make a search or using it as a default browser this version (6.6.1) is not going to work.

Is there some way to just eliminate the whole startpage system?
What use does it serve, especially now?

Just eliminate it and the bookmarks all together.

Find a way for the browsr to store user settings for the chosen search engine in the settings and be done.with it.

**Comment by puppykickr** [comment] 2019-08-11 04:34
Ok, cool.
Have a good trip.

Let me know if/how you want some testing done on 7.1.1 and 8.1.0 when you return.

As I have been using WebApps instead of bookmarks it no longer infuriates me if my bookmarks vanish, hahaha.

This latest update threw me a curve ball, as the homepage was reset.

When I reset the startpage via the homepage, the setting were there but something is off because the searchbar is missing.

I will have to make a screen recording to show it, I think.

**Comment by scoute-dich** [comment] 2019-11-09 10:35
I can not reproduce his. Please test attached apk (just rename) and report if issue still persists.

**Comment by scoute-dich** [comment] 2019-11-09 10:38
I'll close this issue, since it's aduplicate of #331 . Please follow there.

**Closed by scoute-dich** 2019-11-09 10:38 UTC
