### ISSUE TITLE
version 7.2 (105) from google: input bar shows no reaction

### ISSUE THREAD

**Issue by tusch001** [scoute-dich/browser#449] opened 2020-09-28 14:58 UTC
Sorry, it's me again.

As in issue #430 described (at the end) and as it also happened with the debug-apks there: Whatever domain is put in the input field, the page stays on github (the default startpage). More details in #430.

I used the google app (f-droid not available yet) and tested it on 2 phones.

- Android Stock 6.01 (Cat S 60)
- LineageOS 15.1 (Samsung Galaxy S7)

None of my phones have gapps installed, just microG. The LineageOS 15-phone is a clean setup with hardly any third-party apps. On both phones version 7.1 from f-droid works fine.

Is there something I can test?. The only other OS I can install are LineageOS 14, 16 and 17 on another tablet. 

Do you need more details? There is nothing in the logcat.

**Comment by StOrmCatz** [comment] 2020-10-06 07:49
I just wanted to chime in that I can confirm this issue on a tablet running LineageOS 14.1 (Nougat)

**Comment by captbuckrogers25** [comment] 2020-10-08 04:22
Can confirm with Android 8.0 (LG V20) and Kindle Fire HE 10 (7th gen) running Fire IS 5.6.7.0

Same behavior described above.

**Comment by fidelius-dc** [comment] 2020-10-11 18:48
Same isssue here.. Installed from F-Droid on stock Android 8.0, Samsung A3 (SM-A320FL)

**Comment by tusch001** [comment] 2020-10-24 14:50
Just an idea to find the cause:
@captbuckrogers25 / @StOrmCatz / @fidelius-dc : Do you have a typical "google" phone or something modded? Because I have a feeling that none of you has a phone where the original google service framework is active and LineageOS is not a 100% replacement. The only phone where I can get 7.2 running is a new Samsung phone where I haven't found a custom recovery yet. All other of my phones with Android stock are at least rooted and don't have an active original google service framework.

Obviously there were some code changes. Maybe there is unintentionally a dependency on something? 
(I'm thinking about autofill, I vaguely remember there was an issue with some password managers and missing permissions when autofill was introduced some years ago). And we all don't use the latest phones.


@scoute-dich: I'm in no way an expert. I may be just 100 % wrong. It's just a thought.

Stay save.

Patricia

**Comment by daffydock** [comment] 2020-10-24 17:23
Feasible. There could be a dependency missing. I am only stating that because on the phone I have MicroG, I have limited access to some perks from Google but a few apps fail to say, log in, because some java somewhere is missing. But on the same setup where I got the Play Store working, whatever dependencies missing are there and the same app there, works. There could he a number of variables. Main one being, not running on stock.

**Comment by captbuckrogers25** [comment] 2020-10-24 17:26
I'm having the issue on a stock LG V20 running the LG distribution of Android 8.0. While this may not be a full 'Google' phone as a Pixel or similar, I doubt i'm missing any non-specialized dependencies.

**Comment by karcherm** [comment] 2020-11-02 06:28
Same problem on Gigaset S170, Android 7.0, Stock ROM (Play Services running, but Play Store disabled)

**Comment by scoute-dich** [comment] 2021-05-04 07:31
I'll close this issue, since I made a lot of changes concerning styles, themes and the behavior of the toolbar. If there are still problems concerning this, please open a new issue after next update.

**Closed by scoute-dich** 2021-05-04 07:31 UTC
