### ISSUE TITLE
Focus is not on web page after inputting URL or search term in address bar

### ISSUE THREAD

**Issue by StOrmCatz** [scoute-dich/browser#430] opened 2020-07-04 22:42 UTC
**Why/User Benefit/User Problem**

The web page area is not in focus after inputting a site URL or search term in the address bar and hitting enter. Immediately after this event, focus remains in the address bar (denoted by the blinking cursor) which is probably not expected behavior.  In the case where I'm sending a page down key after going to a new address, the input gets consumed by the address bar as opposed to the web page area.

**What/Requirements**

After submitting a value in the address bar and hitting enter, the following should occur:
1. Focus should be put on the web page area
2. Address bar should immediately show page title which is the current behavior when the address bar is not in focus. Currently the address bar remains in focus and shows the URL until you tap out of it

The behavior should be similar to switching tabs which has the page area immediately in focus after a tab change.

**Comment by tusch001** [comment] 2020-07-05 05:59
Additionally suggestion for improvement of the address bar: 
In the step before when you put in the text in the text field:
 
When activating the focus in the address bar for input sometimes (not always) the focus is lost and the user has to tap a second time to start activating the text field. This also looses the selection of the text (or maybe it was not set at all?). So then you have to mark the complete link text to start the input or delete the text with backspace.
I haven't found out when this is. When you start the app with about:blank as startpage the behaviour is a expected but later on while browsing the behaviour is gone. With long link addresses in the text field this are some unneccessary taps / keystrokes.

P.S. Don't just delete the old link text within the input bar with focus (as chrome does). Selecting the old text without erasing gives the user the chance to keep eg the domain name and just change the path while still being able to start a new search without delay.

Thanks for considering.

**Comment by scoute-dich** [comment] 2020-07-13 19:14
[app-debug.apk.zip](https://github.com/scoute-dich/browser/files/4914595/app-debug.apk.zip)
Hi,

I think, with attached apk this issue is solved. If you want to test, just rename file to "app-debug.apk".

**Comment by StOrmCatz** [comment] 2020-07-13 21:52
Thanks for trying to fix this issue.  I've tested the debug APK,  and unfortunately it seems to have broken the URL bar completely in that as soon as I hit enter it simply:
1. Reverts to the original/old URL (before typing into the address bar) and highlights all the text
2. Does not go to the search keyword or URL I typed into the address bar 

The focus also remains in the address bar, just that the text is highlighted instead of the blinking cursor as confirmed by sending a key and seeing it appear in the address bar.

**Comment by scoute-dich** [comment] 2020-07-14 15:53
That's strange on my side everthing works. Anyway I rebuild the apk to test gain:

[app-debug.apk.zip](https://github.com/scoute-dich/browser/files/4919789/app-debug.apk.zip)

**Comment by tusch001** [comment] 2020-07-15 05:18
With the latest apk:
The app starts with the github page but the input in the bar isn't working. Replacing the text with another domain and pressing enter - the page stays on github.

Android Stock 6.01
Cat S 60


Anyway thanks for a great browser.

**Comment by scoute-dich** [comment] 2020-07-15 15:01
That's very strange. I can't reproduce that. At the moment I've less time. So it can take a while until coding goes on.

**Comment by tusch001** [comment] 2020-07-15 15:38
That' totally ok. For me version 7.1 is a great browser. Whenever you find the time. In the next days I can test the latest build on some other devices. Maybe that is helpful. I will report back.

**Comment by StOrmCatz** [comment] 2020-07-15 19:03
I can confirm with tusch001 that the behavior of the address bar is still not working with the latest apk.  The behavior is the same as my earlier posting.

Just to add some device info from my side, I'm using this on a tablet running Android 7.1.2

**Comment by tusch001** [comment] 2020-07-15 22:35
This is a 5 p input in general. I think it may be related.

For quite somr time I have been using your browser as my main browser, mostly on older devices (Android 6 / Lineage 14). There have been some issues going on with the input bar that are hard to track but I consider to be connected to a mixture of 
- being on a very slow connection (2 g)
- having accumulated a too big list of history entries and / or bookmarks
- having used the app for a longer time (or open)

Eg I just closed issue #320 because I thought the problem is gone. But the latest apk here is kind of the same: you type a new input and the new page is not shown

Eg on very slow connection: the page loading is abbreviated but instead of showing a partial loaded text there is only a blank page. In the input bar sometimes the text says something similiar to "de.baumann.browser.view.CompleteAdapter$CompleteItem@133e2b27". Whatever that refers to.

- eg issue 279 where I commented about me using my keyboard app: In no other app there is a problem but the browser crashes repeatedly when the input (a domain with the hitting of one button) is probably too fast

- eg I don't keep a chronic anymore because when I use the browser heavily (and Android doesn't stop the app) and I revisited pages (eg reading tagesschau.de) the app crashes predictably

I think some of these issues might be related to a dynamic memory / cpu speed thing but esp issue #320 seems related. Maybe it happens only on older devices?

I'm writing this because this doesn't happen right from the start and they are only MINOR Issues. Nevertheless I think they should be mentioned. I think you might not beware of this since you once mentioned having access only to newer devices and using the emulator (maybe I'm wrong).
If it is unrelated - please ignore.

Have a good night.

**Comment by tusch001** [comment] 2020-07-17 12:58
FYI:
latest Apk works on a Samsung Galaxy S10 on Android 10 Stock, but 
doesn't work on
- Android Stock 8.0.0 on a Cat S41
- under Lineage 14 (Android 7.1.2) on a Samsung Tablet (SM-p605)

**Comment by scoute-dich** [comment] 2020-07-17 15:26
I autofill could be the problem for older devices.
[app-debug.apk.zip](https://github.com/scoute-dich/browser/files/4938594/app-debug.apk.zip)

**Comment by tusch001** [comment] 2020-07-17 15:56
Still no reaction: After input of the (new) domain and pressing enter the keyboard is hidden and the old input in the bar is completely selected. The bar is visible, as in not hidden. But no browsing to the new page. The old github page stays unchanged. Also no (new) entry in history.

I even installed the original Google Latin IME Keyboard just to make sure it's not my keyboard app.

Only tested on Stock Android 6.0.1 with microG instead of Google Apps.


You wrote you are busy at the moment. Take your time. It needs no fixing today as version 7.1 is usable.

**Comment by tusch001** [comment] 2020-07-17 16:19
For clarification I should also mention that my keyboard app is NOT using autofill. When I enter a complete domain with a long-press tap it works as if I'm hitting the letters very fast on the keyboard. I don't want to mislead you in your search for the cause.

**Comment by scoute-dich** [comment] 2020-08-11 20:55
You can test attached apk-file and report back.
[app-debug.apk.zip](https://github.com/scoute-dich/browser/files/5059422/app-debug.apk.zip)

**Comment by tusch001** [comment] 2020-08-12 02:46
Thanks for spending your vacation t

**Comment by StOrmCatz** [comment] 2020-10-06 02:28
In the case the issue with the latest code change resulting in the the non-responsive URL bar cannot be figured out, here is an idea for a possible workaround:

It appears that switching tabs correctly focuses the page area. Might it be possible to initiate a tab switch to itself once an address is inputted? This should be seamless to the user and still achieve the desired result.

**Comment by scoute-dich** [comment] 2021-05-04 07:31
I'll close this issue, since I made a lot of changes concerning styles, themes and the behavior of the toolbar. If there are still problems concerning this, please open a new issue after next update.

**Closed by scoute-dich** 2021-05-04 07:31 UTC
