### ISSUE TITLE
app crashes when I click the folder option

### ISSUE THREAD

**Issue by kingdidi** [scoute-dich/browser#110] opened 2018-02-28 20:38 UTC
#### Expected behavior
I  expected that if I access a webpage page that the panel to input another webpage will still be visible 

#### Actual behavior
When I access a webpage and scrool up or down the panel to enter web address disappears.

#### How to reproduce
- Download app from google playstore
- launch app
- swipe up from the web address input panel to reveal open tab control panel or click on the 3 dots and select the option open tab control
-click on the folder icon and the app crashes
* Browser: Htc M7
* Operating system: Android 6.0.1
* App version: 5.3.1

Video recording

 https://youtu.be/YQOWNLfGkig

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@kingdidi/the-panel-to-input-web-address-disappears-on-the-browser-when-i-access-a-website-and-scroll-up-or-down">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by scoute-dich** [comment] 2018-02-28 20:57
Have you granted permissions? I'm already on the next b version and only have a phone with Android Oreo. But I'll look of I've forgotten somewhere to implement permission requesting.

**Comment by kingdidi** [comment] 2018-02-28 21:06
Yes permission was enabled.
Storage and location precisely

**Comment by scoute-dich** [comment] 2018-03-01 05:26
Thanks. I'll upload here a test apk, of you want to try.

**Comment by scoute-dich** [comment] 2018-03-01 10:16
If you want, you can test the latest release (apk is attached) or just wait for the update, which I released an hour ago. If the problem is solved, please close the issue. Thanks in advance.

**Comment by kingdidi** [comment] 2018-03-01 10:27
Didn't get the attached file

**Comment by scoute-dich** [comment] 2018-03-01 15:29
It's in the release section of this project.

**Comment by scoute-dich** [comment] 2018-03-04 19:41
[app-debug.apk.zip](https://github.com/scoute-dich/browser/files/1778853/app-debug.apk.zip)
Perhaps you can test this file and report back.

**Comment by scoute-dich** [comment] 2018-03-13 19:05
If this is still a problem on the latest version. Please reopen the issue.

**Closed by scoute-dich** 2018-03-13 19:05 UTC

**Comment by onozasi** [comment] 2018-04-10 08:54
Hi @scoute-dich seems this issue persist on the latest version

**Comment by scoute-dich** [comment] 2018-04-10 19:31
Which Android version? Can you provide a logcat?
